"""Add date column to time_slots table

Revision ID: 865a8746d1fe
Revises: 
Create Date: 2025-04-06 13:17:12.308180

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '865a8746d1fe'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_appointments_id', table_name='appointments')
    op.drop_table('appointments')
    op.add_column('time_slots', sa.Column('date', sa.Date(), nullable=True))
    op.drop_column('time_slots', 'end_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_slots', sa.Column('end_time', sa.VARCHAR(), nullable=True))
    op.drop_column('time_slots', 'date')
    op.create_table('appointments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('appointment_time', sa.DATETIME(), nullable=True),
    sa.Column('patient_id', sa.INTEGER(), nullable=True),
    sa.Column('doctor_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_appointments_id', 'appointments', ['id'], unique=False)
    # ### end Alembic commands ###
